name: DataX
options:
  bundleIdPrefix: com.datax
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: DataX
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  DataX:
    type: application
    platform: macOS
    sources:
      - path: DataX
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.datax.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_CFBundleDisplayName: DataX
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026. All rights reserved."
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
